apiVersion: batch/v1
kind: Job
metadata:
  name: ml-training-job
spec:
  template:
    spec:
      containers:
      - name: ml-trainer
        image: ml-trainer:latest
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4
